apiVersion: v1
kind: Service
metadata:
  name: valkyrie-postgres
  labels:
    app: valkyrie
spec:
  selector:
    app: valkyrie
    component: postgres
  ports:
    - name: http
      port: 5432
      targetPort: {{ .Values.postgres.port | default 5432 }}
