apiVersion: v1
kind: Service
metadata:
  name: valkyrie-postgres
  labels:
    app: valkyrie
spec:
  type: NodePort
  ports:
    - name: "postgres-port"
      port: {{ .Values.postgres.port | default 5432 }}
      targetPort: {{ .Values.postgres.port | default 5432 }}
      protocol: TCP
  selector:
    component: postgres
