apiVersion: v1
data:
  traefik.yml: |
    global:
      sendAnonymousUsage: false

    api:
      dashboard: true

    entryPoints:
      web:
        address: ":80"
      dashboard:
        address: ":8080"


    providers:
      kubernetesIngress: {}

kind: ConfigMap
metadata:
  name: traefik-proxy-cm0
  labels:
    app: valkyrie
