apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: valkyrie
    component: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-http-service
spec:
  type: LoadBalancer
  ports:
    - targetPort: web
      port: 80
  selector:
    app: valkyrie
    component: traefik
