apiVersion: v1
kind: Service
metadata:
  name: valkyrie-service
  labels:
    app: valkyrie
spec:
  selector:
    component: server
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https
