apiVersion: v1
kind: ServiceAccount
metadata:
  name: valkyrie-acc
  namespace: {{ .Values.namespace | default "default" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: valkyrie-role
  namespace: {{ .Values.namespace | default "default" }}
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "persistentvolumeclaims", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: valkyrie-account-binding
  namespace: {{ .Values.namespace | default "default" }}
subjects:
- kind: ServiceAccount
  name: valkyrie-acc
  namespace: {{ .Values.namespace | default "default" }}
roleRef:
  kind: Role
  name: valkyrie-role
  apiGroup: rbac.authorization.k8s.io
