global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['valkyrie-otel-collector:9090']

  # - job_name: 'tetragon-direct'
  #   static_configs:
  #     - targets: ['tetragon:9091']
