openapi: 3.0.2
info:
  title: API Title
  version: 0.0.1
  license:
    name: MIT
    url: https://github.com/deepakdinesh1123/valkyrie/blob/main/LICENSE
servers:
  - url: http://usevalkyrie.odin.org/api/v1
paths:
  /executions/execute:
    $ref: paths/executions_execute.yml
  /jobs/execution:
    $ref: paths/jobs_execution.yml
  /executions:
    $ref: paths/executions.yml
  /jobs/{JobId}/executions:
    $ref: paths/jobs_{JobId}_executions.yml
  /executions/{execId}:
    $ref: paths/executions_{execId}.yml
  /executions/jobs/{JobId}:
    $ref: paths/executions_jobs_{JobId}.yml
  /version:
    $ref: paths/version.yml
  /execution/config:
    $ref: paths/execution_config.yml
  /languages:
    $ref: paths/languages.yml
  /search/system:
    $ref: paths/search_system.yml
  /search/language:
    $ref: paths/search_language.yml
  /packages/exist/:
    $ref: paths/packages_exist_.yml
