openapi: 3.0.2
info:
  title: API Title
  version: 0.0.1
servers:
  - url: http://localhost:8080/api/v1
paths:
  /execution/execute/:
    $ref: paths/execution_execute_.yml
  /execition/{execution_id}/:
    $ref: paths/execition_{execution_id}_.yml
  /execution/:
    $ref: paths/execution_.yml
  /execution/results/:
    $ref: paths/execution_results_.yml
  /search/:
    $ref: paths/search.yml
