services:
  odin:
    build:
      context: .
      dockerfile: build/package/dockerfiles/odin.server.dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    command: ["server", "start"]
    ports:
      - "8080:8080"
  
  odin-worker:
    build:
      context: .
      dockerfile: build/package/dockerfiles/odin.worker.dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      odin:
        condition: service_started
    deploy:
      replicas: 3
    command: ["worker", "start"]

  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
