site_name: Valkyrie
site_description: Valkyrie Documentation
strict: true
site_url: https://deepakdinesh1123.github.io/valkyrie/

repo_name: deepakdinesh1123/valkyrie
repo_url: https://github.com/deepakdinesh1123/valkyrie
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/odin.svg
  favicon: images/odin.svg
  palette:
      scheme: slate
      primary: black
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - Valkyrie:
      - Home: valkyrie/index.md
      - Architecture: valkyrie/architecture.md
      - Installation: valkyrie/installation.md
      - Setup:
          - Home: valkyrie/setup/index.md
          - Docker: valkyrie/setup/docker.md
      - Usage:
          - Home: valkyrie/examples/index.md
          - Examples: valkyrie/examples/examples.md
      - Deployment:
          - Home: valkyrie/deployment/index.md
          - Nixery: valkyrie/deployment/nixery.md
          - GCP: valkyrie/deployment/gcp.md
      - Contributing: valkyrie/contributing.md
  - Blog: blog/index.md

markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji # noqa
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # noqa
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - privacy
  - search
  - blog
  - minify:
      minify_html: true

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepakdinesh1123/valkyrie
extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright &copy; 2024 Odin
