site_name: Valkyrie
site_description: Valkyrie Documentation
strict: true
site_url: https://deepakdinesh1123.github.io/valkyrie/

repo_name: deepakdinesh1123/valkyrie
repo_url: https://github.com/deepakdinesh1123/valkyrie
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: docs/overrides
  logo: images/odin.svg
  favicon: images/odin.svg
  palette:
      scheme: slate
      primary: black
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  language: en
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.expand
    - navigation.indexes
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.sections
    - navigation.tracking
    - navigation.top
    - toc.follow

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

nav:
  - Home: index.md
  - Valkyrie: valkyrie/index.md
  - Odin:
      - Home: valkyrie/odin/index.md
      - Architecture: valkyrie/odin/architecture.md
      - Installation: valkyrie/odin/installation.md
      - Setup:
          - Home: valkyrie/odin/setup/index.md
          - Standalone: valkyrie/odin/setup/standalone.md
          - Podman: valkyrie/odin/setup/podman.md
          - Docker: valkyrie/odin/setup/docker.md
          - NSJail: valkyrie/odin/setup/nsjail.md
          - Native: valkyrie/odin/setup/native.md
      - Contributing: valkyrie/odin/contributing.md
      - Examples: valkyrie/odin/examples.md
      - Deployment:
          - Home: valkyrie/odin/deployment/index.md
          - AWS:
              - Tofu Deployment: valkyrie/odin/deployment/aws/AWS_deployment.md
              - Odin Server: valkyrie/odin/deployment/aws/server.md
              - Shared Nix Store: valkyrie/odin/deployment/aws/shared_nix_store.md
              - Odin Worker: valkyrie/odin/deployment/aws/worker.md
          - GCP:
              - Tofu Deployment: valkyrie/odin/deployment/gcp/GCP_deployment.md
              - Odin Server: valkyrie/odin/deployment/gcp/server.md
              - Shared Nix Store: valkyrie/odin/deployment/gcp/shared_nix_store.md
              - Odin Worker: valkyrie/odin/deployment/gcp/worker.md
  - Blog: blog/index.md


markdown_extensions:
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - privacy
  - search
  - blog
  - minify:
      minify_html: true

extra:
  status:
    new: Recently added
    deprecated: Deprecated
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepakdinesh1123/valkyrie
extra_css:
  - stylesheets/extra.css

copyright: >
  Copyright &copy; 2024 Odin
