apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: valkyrie
deploy:
  helm:
    releases:
      - name: valkyrie
        chartPath: deployments/helm/valkyrie
        valuesFiles:
          - deployments/helm/valkyrie/values.yaml
        version: 0.1.0
build:
  local:
    useBuildkit: true
  tagPolicy:
    envTemplate:
      template: "{{.VERSION}}"
  artifacts:
    - image: valkyrie
      context: .
      docker:
        dockerfile: builds/images/packages/valkyrie.dockerfile
    - image: valkyrie-store
      context: .
      docker:
        dockerfile: builds/images/store/store.k8s.dockerfile
    - image: valkyrie-devpi
      context: .
      docker:
        dockerfile: builds/images/devpi.dockerfile
    - image: valkyrie-sandbox
      context: .
      docker:
        dockerfile: builds/images/sandbox/ubuntu.dockerfile
        buildArgs:
          NIX_CACHE_PUBLIC_KEY: "valkyrie-store:16vPF/cjrSV3z11yd6dkSf+rlxxM1g80Mx38gIv6JqA="
    - image: valkyrie-execution
      context: .
      docker:
        dockerfile: builds/images/execution/ubuntu.dockerfile
        buildArgs:
          NIX_CACHE_PUBLIC_KEY: "valkyrie-store:16vPF/cjrSV3z11yd6dkSf+rlxxM1g80Mx38gIv6JqA="
