apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: valkyrie
build:
  artifacts:
    - image: odin
      context: .
      docker:
        dockerfile: build/package/dockerfiles/odin.dockerfile
    - image: geri
      context: .
      docker:
        dockerfile: build/package/dockerfiles/geri.dockerfile
manifests:
  rawYaml:
    - deployments/kubernetes/manifests/*/*.yaml
