nix_channel: https://nixos.org/channels/nixos-24.05

languages:
  - name: python
    extension: py
    monacoLanguage: python
    versions:
      - nixPackage: "python312"
        version: "3.12"
        default: true
      - nixPackage: "python311"
        version: "3.11"
      - nixPackage: "python310"
        version: "3.10"
    template: |
      {{ define "execute" }} python main.py {{ end }}
    deps:
      - numpy
      - tensorflow
      - torch
      - pandas
      - requests
      - openai
    defaultCode: |
      print("Hello World")

  - name: go
    extension: go
    monacoLanguage: go
    versions:
      - nixPackage: "go_1_22"
        version: "1.22"
      - nixPackage: "go_1_21"
        version: "1.21"
        default: true
    template: |
      {{ define "execute" }} go run main.go {{ end }}
    defaultCode: |
      package main
      import "fmt"

      func main() {
          fmt.Println("Hello, World!")
      }

packages:
  - sqlite
  - rocksdb
  - pkg-config