openapi: '3.0.2'
info:
  title: API Title
  version: '0.0.1'
servers:
  - url: http://localhost:8080/api/v1
paths:
  /execute:
    post:
      summary: Execute a script
      description: Execute a script
      operationId: execute
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExecutionRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /execute/{execution_id}:
    get:
      summary: Get execution result
      description: Get execution result
      operationId: getExecutionResult
      parameters:
        - name: execution_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExecutionResult'
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    EnvironmentVariable:
      type: object
      properties:
        key:
          type: string
        value:
          type: string
    Script:
      type: object
      properties:
        name:
          type: string
        script:
          type: string
    Environment:
      type: object
      properties:
        environment_variables:
          type: array
          items:
            $ref: '#/components/schemas/EnvironmentVariable'
        packages:
          type: array
          items:
            type: string
        enterShell:
          type: string
        scripts:
          type: array
          items:
            $ref: '#/components/schemas/Script'
    File:
      type: object
      properties:
        name:
          type: string
        content:
          type: string
    ExecutionRequest:
      type: object
      required:
        - devenv
        - file
      properties:
        devenv:
          type: string
        file:
          $ref: '#/components/schemas/File'
    ExecutionResult:
      type: object
      required:
        - execution_id
      properties:
        execution_id:
          type: string
        status:
          type: string
        result:
          type: string
    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        
        
        
        
        
