// Code generated by ogen, DO NOT EDIT.
package api

type CancelExecutionJobRes interface {
	cancelExecutionJobRes()
}

type CreateSandboxRes interface {
	createSandboxRes()
}

type DeleteExecutionJobRes interface {
	deleteExecutionJobRes()
}

type ExecuteRes interface {
	executeRes()
}

type FetchFlakeRes interface {
	fetchFlakeRes()
}

type GetAllExecutionJobsRes interface {
	getAllExecutionJobsRes()
}

type GetAllExecutionsRes interface {
	getAllExecutionsRes()
}

type GetAllLanguageVersionsRes interface {
	getAllLanguageVersionsRes()
}

type GetAllLanguagesRes interface {
	getAllLanguagesRes()
}

type GetAllVersionsRes interface {
	getAllVersionsRes()
}

type GetExecutionConfigRes interface {
	getExecutionConfigRes()
}

type GetExecutionJobByIdRes interface {
	getExecutionJobByIdRes()
}

type GetExecutionResultByIdRes interface {
	getExecutionResultByIdRes()
}

type GetExecutionsForJobRes interface {
	getExecutionsForJobRes()
}

type GetLanguageByIdRes interface {
	getLanguageByIdRes()
}

type GetLanguageVersionByIdRes interface {
	getLanguageVersionByIdRes()
}

type GetSandboxRes interface {
	getSandboxRes()
}

type GetVersionRes interface {
	getVersionRes()
}
