// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelExecutionJobOperation     OperationName = "CancelExecutionJob"
	CreateSandboxOperation          OperationName = "CreateSandbox"
	DeleteExecutionJobOperation     OperationName = "DeleteExecutionJob"
	ExecuteOperation                OperationName = "Execute"
	FetchFlakeOperation             OperationName = "FetchFlake"
	GetAllExecutionJobsOperation    OperationName = "GetAllExecutionJobs"
	GetAllExecutionsOperation       OperationName = "GetAllExecutions"
	GetAllLanguageVersionsOperation OperationName = "GetAllLanguageVersions"
	GetAllLanguagesOperation        OperationName = "GetAllLanguages"
	GetAllVersionsOperation         OperationName = "GetAllVersions"
	GetExecutionConfigOperation     OperationName = "GetExecutionConfig"
	GetExecutionJobByIdOperation    OperationName = "GetExecutionJobById"
	GetExecutionResultByIdOperation OperationName = "GetExecutionResultById"
	GetExecutionsForJobOperation    OperationName = "GetExecutionsForJob"
	GetLanguageByIdOperation        OperationName = "GetLanguageById"
	GetLanguageVersionByIdOperation OperationName = "GetLanguageVersionById"
	GetLoginConfigOperation         OperationName = "GetLoginConfig"
	GetSandboxOperation             OperationName = "GetSandbox"
	GetValkyrieTokenOperation       OperationName = "GetValkyrieToken"
	GetVersionOperation             OperationName = "GetVersion"
	HealthOperation                 OperationName = "Health"
	OauthCallbackOperation          OperationName = "OauthCallback"
)
