type: object
properties:
  environment_variables:
    type: array
    items:
      $ref: ./EnvironmentVariable.yml
  packages:
    type: array
    items:
      type: string
  enterShell:
    type: string
  scripts:
    type: array
    items:
      $ref: ./Script.yml
