type: object
properties:
  environment_variables:
    type: array
    items:
      $ref: ./EnvironmentVariable.yml
  languageDependencies:
    type: array
    items:
      type: string
  systemDependencies:
    type: array
    items:
      type: string
  setup:
    type: string
