apiVersion: v1
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
kind: Secret
metadata:
  creationTimestamp: null
  name: registry-creds
  labels:
    {{- include "odin.labels" . | nindent 4}}
type: kubernetes.io/dockerconfigjson
