// Code generated by ogen, DO NOT EDIT.
package api

type CancelExecutionJobRes interface {
	cancelExecutionJobRes()
}

type DeleteExecutionJobRes interface {
	deleteExecutionJobRes()
}

type DeleteExecutionWorkerRes interface {
	deleteExecutionWorkerRes()
}

type ExecuteRes interface {
	executeRes()
}

type GetAllExecutionJobsRes interface {
	getAllExecutionJobsRes()
}

type GetAllExecutionsRes interface {
	getAllExecutionsRes()
}

type GetAllLanguagesRes interface {
	getAllLanguagesRes()
}

type GetExecutionConfigRes interface {
	getExecutionConfigRes()
}

type GetExecutionJobByIdRes interface {
	getExecutionJobByIdRes()
}

type GetExecutionResultByIdRes interface {
	getExecutionResultByIdRes()
}

type GetExecutionWorkersRes interface {
	getExecutionWorkersRes()
}

type GetExecutionsForJobRes interface {
	getExecutionsForJobRes()
}

type GetVersionRes interface {
	getVersionRes()
}
