// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Execute implements execute operation.
//
// Execute a script.
//
// POST /execution/execute/
func (UnimplementedHandler) Execute(ctx context.Context, req *ExecutionRequest) (r ExecuteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExecutionResult implements getExecutionResult operation.
//
// Get execution result.
//
// GET /execution/{executionId}/
func (UnimplementedHandler) GetExecutionResult(ctx context.Context, params GetExecutionResultParams) (r GetExecutionResultRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExecutionResults implements getExecutionResults operation.
//
// Get all execution results.
//
// GET /execution/results/
func (UnimplementedHandler) GetExecutionResults(ctx context.Context) (r GetExecutionResultsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExecutions implements getExecutions operation.
//
// Get all executions.
//
// GET /execution/
func (UnimplementedHandler) GetExecutions(ctx context.Context) (r GetExecutionsRes, _ error) {
	return r, ht.ErrNotImplemented
}
