// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelJob implements cancelJob operation.
	//
	// Cancel Job.
	//
	// PUT /executions/{JobId}/
	CancelJob(ctx context.Context, params CancelJobParams) (CancelJobRes, error)
	// DeleteJob implements deleteJob operation.
	//
	// Delete job.
	//
	// DELETE /executions/{JobId}/
	DeleteJob(ctx context.Context, params DeleteJobParams) (DeleteJobRes, error)
	// Execute implements execute operation.
	//
	// Execute a script.
	//
	// POST /executions/execute/
	Execute(ctx context.Context, req *ExecutionRequest) (ExecuteRes, error)
	// GetAllExecutionResults implements getAllExecutionResults operation.
	//
	// Get all execution results.
	//
	// GET /executions/results/
	GetAllExecutionResults(ctx context.Context, params GetAllExecutionResultsParams) (GetAllExecutionResultsRes, error)
	// GetAllExecutions implements getAllExecutions operation.
	//
	// Get all executions.
	//
	// GET /executions/
	GetAllExecutions(ctx context.Context, params GetAllExecutionsParams) (GetAllExecutionsRes, error)
	// GetExecutionConfig implements getExecutionConfig operation.
	//
	// Get execution config.
	//
	// GET /execution/config/
	GetExecutionConfig(ctx context.Context) (GetExecutionConfigRes, error)
	// GetExecutionResultsById implements getExecutionResultsById operation.
	//
	// Get execution result.
	//
	// GET /executions/{JobId}/
	GetExecutionResultsById(ctx context.Context, params GetExecutionResultsByIdParams) (GetExecutionResultsByIdRes, error)
	// GetExecutionWorkers implements getExecutionWorkers operation.
	//
	// Get all execution workers.
	//
	// GET /executions/workers
	GetExecutionWorkers(ctx context.Context, params GetExecutionWorkersParams) (GetExecutionWorkersRes, error)
	// GetVersion implements getVersion operation.
	//
	// Get version.
	//
	// GET /version/
	GetVersion(ctx context.Context) (GetVersionRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
