// Code generated by ogen, DO NOT EDIT.
package api

type DeleteExecutionRes interface {
	deleteExecutionRes()
}

type ExecuteRes interface {
	executeRes()
}

type GetExecutionConfigRes interface {
	getExecutionConfigRes()
}

type GetExecutionResultRes interface {
	getExecutionResultRes()
}

type GetExecutionWorkersRes interface {
	getExecutionWorkersRes()
}

type GetExecutionsRes interface {
	getExecutionsRes()
}

type GetVersionRes interface {
	getVersionRes()
}
