// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Execute implements execute operation.
//
// Execute a script.
//
// POST /execute
func (UnimplementedHandler) Execute(ctx context.Context, req *ExecutionRequest) (r ExecuteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetExecutionResult implements getExecutionResult operation.
//
// Get execution result.
//
// GET /execute/{execution_id}
func (UnimplementedHandler) GetExecutionResult(ctx context.Context, params GetExecutionResultParams) (r GetExecutionResultRes, _ error) {
	return r, ht.ErrNotImplemented
}
