authors:
  deepak:
   name: Deepak
   description: Developer
   avatar: https://avatars.githubusercontent.com/u/52698821
   url: https://github.com/deepakdinesh1123
  sujay:
    name: Sujay
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/89687737
    url: https://github.com/Sujay-J-Reddy
  manoj:
    name: Manoj
    description: Developer
    avatar: https://avatars.githubusercontent.com/u/71307033
    url: https://github.com/ManojHA24