// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sandbox.sql

package db

import (
	"context"

	jsonschema "github.com/deepakdinesh1123/valkyrie/internal/odin/db/jsonschema"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearSandboxes = `-- name: ClearSandboxes :exec
delete from sandboxes
`

func (q *Queries) ClearSandboxes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearSandboxes)
	return err
}

const getSandbox = `-- name: GetSandbox :one
select sandbox_id, worker_id, started_at, created_at, updated_at, sandbox_url, sandbox_agent_url, password, config, details, current_state
from sandboxes
where  sandbox_id = $1
`

func (q *Queries) GetSandbox(ctx context.Context, sandboxID int64) (Sandbox, error) {
	row := q.db.QueryRow(ctx, getSandbox, sandboxID)
	var i Sandbox
	err := row.Scan(
		&i.SandboxID,
		&i.WorkerID,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SandboxUrl,
		&i.SandboxAgentUrl,
		&i.Password,
		&i.Config,
		&i.Details,
		&i.CurrentState,
	)
	return i, err
}

const insertSandbox = `-- name: InsertSandbox :one
insert into sandboxes (config, details)
values ($1, $2)
returning sandbox_id, worker_id, started_at, created_at, updated_at, sandbox_url, sandbox_agent_url, password, config, details, current_state
`

type InsertSandboxParams struct {
	Config  jsonschema.SandboxConfig  `db:"config" json:"config"`
	Details jsonschema.SandboxDetails `db:"details" json:"details"`
}

func (q *Queries) InsertSandbox(ctx context.Context, arg InsertSandboxParams) (Sandbox, error) {
	row := q.db.QueryRow(ctx, insertSandbox, arg.Config, arg.Details)
	var i Sandbox
	err := row.Scan(
		&i.SandboxID,
		&i.WorkerID,
		&i.StartedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SandboxUrl,
		&i.SandboxAgentUrl,
		&i.Password,
		&i.Config,
		&i.Details,
		&i.CurrentState,
	)
	return i, err
}

const markSandboxRunning = `-- name: MarkSandboxRunning :exec
update sandboxes set
started_at = now(),
sandbox_url = $2,
password = $3,
sandbox_agent_url = $4,
current_state = 'running',
updated_at = now()
where sandbox_id = $1
`

type MarkSandboxRunningParams struct {
	SandboxID       int64       `db:"sandbox_id" json:"sandbox_id"`
	SandboxUrl      pgtype.Text `db:"sandbox_url" json:"sandbox_url"`
	Password        []byte      `db:"password" json:"password"`
	SandboxAgentUrl pgtype.Text `db:"sandbox_agent_url" json:"sandbox_agent_url"`
}

func (q *Queries) MarkSandboxRunning(ctx context.Context, arg MarkSandboxRunningParams) error {
	_, err := q.db.Exec(ctx, markSandboxRunning,
		arg.SandboxID,
		arg.SandboxUrl,
		arg.Password,
		arg.SandboxAgentUrl,
	)
	return err
}

const updateSandboxPassword = `-- name: UpdateSandboxPassword :exec
update sandboxes set
password = $2
where sandbox_id = $1
`

type UpdateSandboxPasswordParams struct {
	SandboxID int64  `db:"sandbox_id" json:"sandbox_id"`
	Password  []byte `db:"password" json:"password"`
}

func (q *Queries) UpdateSandboxPassword(ctx context.Context, arg UpdateSandboxPasswordParams) error {
	_, err := q.db.Exec(ctx, updateSandboxPassword, arg.SandboxID, arg.Password)
	return err
}

const updateSandboxStartTime = `-- name: UpdateSandboxStartTime :exec
update sandboxes set
started_at = $2
where sandbox_id = $1
`

type UpdateSandboxStartTimeParams struct {
	SandboxID int64              `db:"sandbox_id" json:"sandbox_id"`
	StartedAt pgtype.Timestamptz `db:"started_at" json:"started_at"`
}

func (q *Queries) UpdateSandboxStartTime(ctx context.Context, arg UpdateSandboxStartTimeParams) error {
	_, err := q.db.Exec(ctx, updateSandboxStartTime, arg.SandboxID, arg.StartedAt)
	return err
}

const updateSandboxState = `-- name: UpdateSandboxState :exec
update  sandboxes set
current_state = $2,
details = $3
where sandbox_id =  $1
`

type UpdateSandboxStateParams struct {
	SandboxID    int64                     `db:"sandbox_id" json:"sandbox_id"`
	CurrentState string                    `db:"current_state" json:"current_state"`
	Details      jsonschema.SandboxDetails `db:"details" json:"details"`
}

func (q *Queries) UpdateSandboxState(ctx context.Context, arg UpdateSandboxStateParams) error {
	_, err := q.db.Exec(ctx, updateSandboxState, arg.SandboxID, arg.CurrentState, arg.Details)
	return err
}
