languages:
  - name: generic
    extension: none
    versions:
      - default: true

  - name: python
    extension: py
    monacoLanguage: python
    versions:
      - nixPackage: "python314"
        default: true
        version: "3.14"
      - nixPackage: "python313"
        version: "3.13"
      - nixPackage: "python312Full"
        version: "3.12"
      - nixPackage: "python311"
        version: "3.11"
      - nixPackage: "python310"
        version: "3.10"
    template: |
      {{  define "execute" }} uv run {{- range .LanguageDependencies }} --with "{{.}}" {{ end }} {{- if not .IsFlake }} --index {{ .PkgIndex }} {{- end }} main.py {{ end }}
    defaultCode: |
      print("Hello World")

  - name: go
    extension: go
    monacoLanguage: go
    versions:
      - nixPackage: "go"
        default: true
        version: "1.24.3"
      - nixPackage: "go_1_23"
        version: "1.23.9"
    template: |
      {{ define "compile" }} go build main.go {{ .CompilerArgs }}{{ end }}
      {{ define "execute" }} ./main {{ end }}
    defaultCode: |
      package main
      import "fmt"

      func main() {
          fmt.Println("Hello, World!")
      }

  - name: bash
    extension: bash
    monacoLanguage: shell
    versions:
      - nixPackage: "bash"
        default: true
        version: "5.2"
    template: |
      {{ define "execute" }} bash main.bash {{ end }}
    defaultCode: |
      echo hello

  - name: bun
    extension: js
    monacoLanguage: javascript
    versions:
      - nixPackage: "bun"
        default: true
        version: "1.2.14"
    template: |
      {{ define "execute" }} bun run main.js {{ end }}
    defaultCode: |
      console.log("Hello World!")

  - name: deno
    extension: ts
    monacoLanguage: typescript
    versions:
      - nixPackage: "deno"
        default: true
        version: "2.3.5"
    template: |
      {{ define "execute" }} deno run main.ts {{ end }}
    defaultCode: |
      console.log("Hello World");

  - name: node
    extension: js
    monacoLanguage: javascript
    versions:
      - nixPackage: "nodejs_24"
        version: "24.1.0"
      - nixPackage: "nodejs_22"
        version: "22.14.0"
      - nixPackage: "nodejs_20"
        default: true
        version: "20.19.2"
    template: |
      {{ define "execute" }} node main.js {{ end }}
    defaultCode: |
      console.log("Hello World!");

  - name: rust
    extension: rs
    monacoLanguage: rust
    versions:
      - nixPackage: "rustc"
        default: true
        version: "1.86.0"
    template: |
      {{ define "compile" }} rustc main.rs {{ .CompilerArgs }} {{ end }}
      {{ define "execute" }} ./main {{ end }}
    defaultCode: |
      fn main() {
          println!("Hello, world!");
      }

  - name: sql
    extension: sql
    monacoLanguage: sql
    versions:
      - nixPackage: "sqlite"
        default: true
        version: "3.48.0"
    template: |
      {{ define "execute" }} sqlite3 sample.db < main.sql {{ end }}
    defaultCode: |
      CREATE TABLE employees (
          id INT PRIMARY KEY,
          name VARCHAR(100),
          salary DECIMAL(10, 2)
      );
