nix_channel: 24.11

languages:
  - name: python
    extension: py
    monacoLanguage: python
    versions:
      - nixPackage: "python312"
        searchQuery: "python312Packages"
        default: true
      - nixPackage: "python311"
        searchQuery: "python311Packages"
    template: |
      {{ define "LangSetup" }}
      {{- if .IsFlake -}}
        uv
        {{- .LangNixPkg -}}
      {{- else -}}
        uv {{ .LangNixPkg }}
      {{- end -}}
      {{ end }}

      {{  define "execute" }} uv run {{- range .LanguageDependencies }} --with "{{.}}" {{ end }} --index {{ .PkgIndex }} main.py {{ end }}
    defaultCode: |
      print("Hello World")

  - name: go
    extension: go
    monacoLanguage: go
    versions:
      - nixPackage: "go_1_22"
        searchQuery: "goPackages"
    template: |
      {{ define "compile" }} go build main.go {{ .CompilerArgs }}{{ end }}
      {{ define "execute" }} ./main {{ end }}
    defaultCode: |
      package main
      import "fmt"

      func main() {
          fmt.Println("Hello, World!")
      }

  - name: bash
    extension: bash
    monacoLanguage: shell
    versions:
      - nixPackage: "bash"
        default: true
        searchQuery: "bashPackages"
    template: |
      {{ define "execute" }} bash main.bash {{ end }}
    defaultCode: |
      echo hello

  - name: bun
    extension: js
    monacoLanguage: javascript
    versions:
      - nixPackage: "bun"
        default: true
        searchQuery: "bunPackages"
    template: |
      {{ define "execute" }} bun run main.js {{ end }}
    defaultCode: |
      console.log("Hello World!")

  - name: deno
    extension: ts
    monacoLanguage: typescript
    versions:
      - nixPackage: "deno"
        default: true
        searchQuery: "deno"
    template: |
      {{ define "execute" }} deno run main.ts {{ end }}
    defaultCode: |
      console.log("Hello World");

  - name: node
    extension: js
    monacoLanguage: javascript
    versions:
      - nixPackage: "nodejs_22"
        searchQuery: "nodePackages"
      - nixPackage: "nodejs_20"
        searchQuery: "nodePackages"
      - nixPackage: "nodejs_18"
        searchQuery: "nodePackages"
      - nixPackage: "nodejs_23"
        default: true
        searchQuery: "nodePackages"
    template: |
      {{ define "execute" }} node main.js {{ end }}
    defaultCode: |
      console.log("Hello World!");
    deps:
      - lodash
    
  - name: rust
    extension: rs
    monacoLanguage: rust
    versions:
      - nixPackage: "rustc"
        default: true
        searchQuery: "rust"
    template: |
      {{ define "compile" }} rustc main.rs {{ .CompilerArgs }} {{ end }} 
      {{ define "execute" }} ./main {{ end }}
    defaultCode: |
      fn main() {
          println!("Hello, world!");
      }

  - name: sql
    extension: sql
    monacoLanguage: sql
    versions:
      - nixPackage: "sqlite"
        default: true
        searchQuery: "sql"
    template: |
      {{ define "execute" }} sqlite3 sample.db < main.sql {{ end }}
    defaultCode: |
      CREATE TABLE employees (
          id INT PRIMARY KEY,
          name VARCHAR(100),
          salary DECIMAL(10, 2)
      );

packages:
  - jq
  - ffmpeg
  - git
  - gnumake
  - gnused
  - gnutar
  - gzip
  - curl
  - wget
  - bzip2
  - sqlite
  - gcc14
  - postgresql
  - vim
  - gnupatch
  - perl
