apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: valkyrie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:16.3-alpine3.20
        envFrom:
        - configMapRef:
            name: postgres-config