apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: valkyrie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.13.3-alpine          
        envFrom:
        - configMapRef:
            name: rabbitmq-config