[project]
name = "docs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "markdown>=3.7",
    "mkdocs-material>=9.5.49",
    "mkdocs-minify-plugin>=0.8.0",
]
