// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Execution struct {
	ID              int32
	ExecutionID     uuid.UUID
	Code            pgtype.Text
	Environment     pgtype.Text
	RequestedAt     pgtype.Timestamp
	Result          pgtype.Text
	ExecutionStatus pgtype.Text
	ExecutedAt      pgtype.Timestamp
}
