// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: package_filters.sql

package db

import (
	"context"
)

type BulkInsertSystemPackageFiltersParams struct {
	FilterType    string `db:"filter_type" json:"filter_type"`
	PackageString string `db:"package_string" json:"package_string"`
}

const getSysPkgFilters = `-- name: GetSysPkgFilters :many
SELECT id, filter_type, package_string, created_at from system_package_filters
`

func (q *Queries) GetSysPkgFilters(ctx context.Context) ([]SystemPackageFilter, error) {
	rows, err := q.db.Query(ctx, getSysPkgFilters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SystemPackageFilter
	for rows.Next() {
		var i SystemPackageFilter
		if err := rows.Scan(
			&i.ID,
			&i.FilterType,
			&i.PackageString,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const truncateSysPkgFilters = `-- name: TruncateSysPkgFilters :exec
TRUNCATE TABLE system_package_filters CASCADE
`

func (q *Queries) TruncateSysPkgFilters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, truncateSysPkgFilters)
	return err
}
